enum ActionTypes {
    // CELL ACTIONS
    SET_CELL = 'SET_CELL',
    // BOARD ACITONS
    MOVE_BOARD_UP = 'MOVE_BOARD_UP',
    MOVE_BOARD_LEFT = 'MOVE_BOARD_LEFT',
    MOVE_BOARD_RIGHT = 'MOVE_BOARD_RIGHT',
    MOVE_BOARD_DOWN = 'MOVE_BOARD_DOWN',
    SET_BOARD_POSITION = 'SET_BOARD_POSITION',
}

export default ActionTypes;